services:
  myapi:
    build:
      context: ..        # le parent de .devcontainer, donc le projet complet
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000 
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: tail -f /dev/null   # garde le conteneur vivant
