name: Test & Format

on:
  pull_request:
    branches: 
      - main

permissions:
  contents: read
  checks: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dotnet-setup 

      - name: Code format check
        run: dotnet format --verify-no-changes

  test:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dotnet-setup

      - name: Test
        run: dotnet test --verbosity normal --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

      - name: Convert TRX to JUnit
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Tests
          path: ./TestResults/*.trx
          reporter: dotnet-trx


